### ISSUE TITLE
Allow to set custom size values

### ISSUE THREAD

**Issue by xvello** [davidosomething/yanjing#3]
Hello again!

For context on this one, I'll be finally moving from MacOS to KDE for my work laptop soon and am working on translating my current workflows. On MacOS, I am currently using ![Rectangle](https://github.com/rxhanson/Rectangle) (a successor to Spectacle) to manage my windows. Like your script, repeated triggers cycle through different window widths, and their sequence (1/2 -> 2/3 -> 1/3) works great for my daily use on a 16/9 screen.

I have patched your script with the following size values after installing:
```js
Yanjing.Sizes = [
  50,
  200 / 3,
  100 / 3,
  100,     // Note the 100%, which would ideally trigger a setMaximised(true,true) in issue #2
];
```

Instead of patching the script after each update, I am wondering whether you'd be open to make the sizes configurable. I looks like scripts can provide a config dialog description and access values with the `readConfig` function (example [videowall plugin](https://invent.kde.org/plasma/kwin/-/tree/master/src/scripts/videowall/contents) in the kwin sources). I that something you'd be open to explore, or review a PR for?

**Comment by davidosomething** [comment]
I have a branch here 
https://github.com/davidosomething/yanjing/compare/add-settings?expand=1
but it doesn't seem to work for me...

want to try fixing it?

**Comment by xvello** [comment]
Of course, I'll give it a look this week !

**Comment by davidosomething** [comment]
Resolved by 06885a4d8535497dffeb0078dfb8131b836d0b24 released as v5.0.0
GUI pull request left open until I can figure out how to make the user experience better

**Comment by xvello** [comment]
It works great, thank you so much!

**Comment by xvello** [comment]
Just installed v5.0.0 from the store, restart to make sure I had to lingering cruft from my manual install, but I still see the configuration icon in the script list, and clicking it leads to an error popup, as no UI file is shipped.

![image](https://user-images.githubusercontent.com/6241083/114093543-87d32480-98bb-11eb-8d4e-fc05916280c9.png)

You'll want to revert your metadata to `X-KDE-ServiceTypes=KWin/Script` only (remove the `KCModule` part) to fix this.

**Comment by davidosomething** [comment]
i think it's there because of the existence of `config/main.xml` which we still need for command line configuration
tried removing in 5.0.1 but still saw the gui there so i'll leave it alone
